apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  # namespace 지정
  namespace: dev
  labels:
    app: myapp
    location: KR
    type: back-end
    anythingyouwant: ok

spec:
  containers:
    - name: nginx-container
      image: nginx
