apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    location: KR
    type: back-end
    anythingyouwant: ok

spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
        # configMap 전체 다 가져오기
        - configMapRef:
            name: app-configmap
        # secret 가져오기
        - secretRef:
            name: app-secret
      env:
        # configMap에서 한 개만 가져오기
        - name: APP_ANY_ENV
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: APP_ANY_ENV
        # secret 한 개만 가져오기
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: app-secret
      # Resource 할당
      resources:
        # 최대치. memory는 넘긴다고 바로 터지진 않고 넘긴 상태가 지속되면 terminated
        limits:
          cpu: "2" # cpu는 vCPU, Core 를 의미함
          memory: "500Mi"
        # 초기 요청량
        requests:
          cpu: "100m" # 0.1 CPU와 동일
          memory: "200Mi"
  # Taint & Toleration
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "SomeValue"
      effect: "NoSchedule"
  # volume 사용
  volumes:
    - name: app-config-volume
      configMap:
        name: app-configmap
    - name: app-secret-volume
      secret:
        secretName: app-secret
